# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Clean Theme"
license = "Apache"
licenselink = "https://github.com/zhaohuabing/hugo-theme-cleanwhite/blob/master/LICENSE"
description = "A clean, elegant blog theme for hugo"

# If porting an existing theme
[original]
  name = "zhaohuabing"
  homepage = "https://github.com/zhaohuabing/hugo-theme-cleanwhite"
